version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: db_annuaire
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks: 
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_annuaire
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
     - dev
  
  www:
    build:
      context: ./server
    container_name: www_annuaire
    ports:
      - "8000:80"
    volumes:
      - ./server/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  cron:
    container_name: cron_annuaire
    build:
      context: ./cron
    depends_on:
      - www
    init: true
    environment:
      - CUSTOM_ENV_VAR=foobar
    volumes:
      - ./cron/crontab:/etc/crontab
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev
   
   
networks:
  dev:

volumes:
  db_data:
