twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: "Bien-Être"
        images_directory: 'http://localhost:8000/uploads/'
        ## images_directory: '%kernel.project_dir%/public/uploads/' ##

when@test:
    twig:
        strict_variables: true
