twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: 'Bien-Être'
        images_directory: 'http://localhost:8000/uploads/'
        logo_directory: 'http://localhost:8000/uploads/logo/'
        avatar_directory: 'http://localhost:8000/uploads/avatar/'
        promotion_directory: 'http://localhost:8000/uploads/promotions/'
        category_directory: 'http://localhost:8000/uploads/category/'
        ## images_directory: '%kernel.project_dir%/public/uploads/'
        ## logo_directory: '%kernel.project_dir%/public/uploads/logo/'
        ## avatar_directory: '%kernel.project_dir%/public/uploads/avatar/'
        ## promotion_directory: '%kernel.project_dir%/public/uploads/promotions/'
        ## category_directory: '%kernel.project_dir%/public/uploads/promotions/'

when@test:
    twig:
        strict_variables: true
